### ISSUE TITLE
Plastic pick-up unknown

### ISSUE THREAD

**Issue by criskolkman** [xirixiz/home-assistant#5]
Hello,

First of all I want to say: GREAT work!!
I'm starting to use your configs but I'm having an issue with the Plastic pick-up day.
It's stating that it's unknown but it seems that the data IS provided by mijnafvalwijzer.nl

![image](https://user-images.githubusercontent.com/17678609/71780549-2f302000-2fc4-11ea-9a7b-f7619ccadb78.png)

And what happens with the following picture when there are 2 pick-ups in one day?
Because GFT and Plastic are always the same day here.

![image](https://user-images.githubusercontent.com/17678609/71780560-5129a280-2fc4-11ea-9d48-0db781cedda2.png)

**Edit:** Got my answer to the above:
![image](https://user-images.githubusercontent.com/17678609/71797281-9cd45e80-304d-11ea-8d51-0da834a04802.png)

**Comment by criskolkman** [comment]
I see below errors in the log.

![image](https://user-images.githubusercontent.com/17678609/71782908-d40c2680-2fdf-11ea-9e1a-c74e091cd568.png)

**Comment by criskolkman** [comment]
I found out that the plastic pick-up is making use of `sensor.trash_drankkarton_kunststof_en_blik` instead of `sensor.trash_plastic` so I changed the code a bit.
Als because of the paper is being handled by a third party here, the sensor for paper is not being created (mijnafvalwijzer.nl probably doesn't have that info).

So instead of showing the paper pick-up in the dashboard I'm now showing the Christmas tree pick-up:

![image](https://user-images.githubusercontent.com/17678609/71812260-061c9780-3077-11ea-8b92-14c6801a489a.png)

In `ui-lovelace.yaml` I changed this:

```
x-afval-images: &afval-images
- state_image:
    'gft': /local/mijnafvalwijzer/gft3.png
    'gft, drankkarton, kunststof en blik': /local/mijnafvalwijzer/gft_plastic3.png
    'drankkarton, kunststof en blik, gft': /local/mijnafvalwijzer/gft_plastic3.png
    'papier': /local/mijnafvalwijzer/papier3.png
    'restafval': /local/mijnafvalwijzer/rest3.png
    'pmd': /local/mijnafvalwijzer/plastic3.png
    'drankkarton, kunststof en blik': /local/mijnafvalwijzer/plastic3.png
    'kerstbomen': /local/mijnafvalwijzer/kerstbomen3.png
    'kerstbomen, drankkarton, kunststof en blik': /local/mijnafvalwijzer/kerstbomen_plastic3.png
    'Geen': /local/mijnafvalwijzer/kliko3.png

# AND:

      - type: glance
        entities:
          - entity: sensor.trash_gft_formatted
            name: GFT
          - entity: sensor.trash_kerstbomen_formatted
            name: Kerstbomen
          - entity: sensor.trash_drankkarton_kunststof_en_blik_formatted
            name: Plastic
          - entity: sensor.trash_restafval_formatted
            name: Restafval
```

My `trash.yaml` now looks like:

```
################################################
## Packages / Trash
################################################
homeassistant:
  customize:
    sensor.trash_today:
      friendly_name: Vandaag
    sensor.trash_tomorrow:
      friendly_name: Morgen
    sensor.trash_next:
      friendly_name: Volgende ophaaldag over

    sensor.trash_gft:
      friendly_name: GFT
      entity_picture: /local/mijnafvalwijzer/gft3.png
    sensor.trash_papier:
      friendly_name: Papier
      entity_picture: /local/mijnafvalwijzer/papier3.png
    sensor.trash_pmd:
      friendly_name: Plastic
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.trash_drankkarton_kunststof_en_blik:
      friendly_name: Plastic
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.trash_restafval:
      friendly_name: Restafval
      entity_picture: /local/mijnafvalwijzer/rest3.png
    sensor.trash_kerstbomen:
      friendly_name: Kerstbomen
      entity_picture: /local/mijnafvalwijzer/kerstbomen3.png

    sensor.trash_gft_formatted:
      entity_picture: /local/mijnafvalwijzer/gft3.png
    sensor.trash_papier_formatted:
      entity_picture: /local/mijnafvalwijzer/papier3.png
    sensor.trash_pmd_formatted:
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.trash_drankkarton_kunststof_en_blik_formatted:
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.trash_restafval_formatted:
      entity_picture: /local/mijnafvalwijzer/rest3.png
    sensor.trash_kerstbomen_formatted:
      entity_picture: /local/mijnafvalwijzer/kerstbomen3.png
    

################################################
## Inputs
################################################
input_boolean:
  trash_moved:
    name: Afval buiten gezet
    initial: false
    icon: mdi:delete-empty
  trash_reminder:
    name: Herinnering afval aan
    initial: true

################################################
## Sensor
################################################
sensor:
  - platform: afvalwijzer
    postcode: !secret postcode
    huisnummer: !secret huisnummer
    #weergave: 'Current'

  - platform: template
    sensors:
      trash_gft_formatted:
        entity_id: sensor.trash_gft
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_gft.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_papier_formatted:
        entity_id: sensor.trash_papier
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_papier.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_pmd_formatted:
        entity_id: sensor.trash_pmd
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_pmd.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_drankkarton_kunststof_en_blik_formatted:
        entity_id: sensor.trash_drankkarton_kunststof_en_blik
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_drankkarton_kunststof_en_blik.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_restafval_formatted:
        entity_id: sensor.trash_restafval
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_restafval.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_kerstbomen_formatted:
        entity_id: sensor.trash_kerstbomen
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_kerstbomen.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
```

And the images (still looking for a better Christmas tree image but it'll do for now...):

kerstbomen3.png:
![image](https://user-images.githubusercontent.com/17678609/71812544-bb4f4f80-3077-11ea-93bb-ce7266c35ac4.png)

kerstbomen_plastic3.png:
![image](https://user-images.githubusercontent.com/17678609/71812579-cf934c80-3077-11ea-93b9-a28737dcf0ae.png)

gft_plastic3.png:
![image](https://user-images.githubusercontent.com/17678609/71812588-d9b54b00-3077-11ea-8c6a-0751ea1e52f0.png)
